# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - JericoFX
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: News 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Fixes
      labels:
        - "*"
